Question1

Numpy array starting from 2 till 50 with a stepsize of 3

In [ ]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

Question2

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
import numpy as np
list1=[]
print("Enter your 5 numbers in your 1st list:")
for i in range(5):
    n=int(input())
    list1.append(n)
a=np.array(list1)
list2=[]
print("Enter your 5 elements in your 2nd list:")
for i in range(5):
    m=int(input())
    list2.append(m)
b=np.array(list2)
c=np.concatenate([a, b])
print("After Concatination:\n",c)
d=np.sort(c)
print("Your sorted array:\n",d)


Enter your 5 numbers in your 1st list:
22222
33333
3333
333
3333
Enter your 5 elements in your 2nd list:
33333
333
1
1
1
After Concatination:
 [22222 33333  3333   333  3333 33333   333     1     1     1]
Your sorted array:
 [    1     1     1   333   333  3333  3333 22222 33333 33333]


Question3

Write a code snippet to find the dimensions of a ndarray and its size

In [7]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(arr)
print("No. of dimensions of the given array is: ", arr.ndim)
print("Size of given array is: ", arr.size)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
No. of dimensions of the given array is:  2
Size of given array is:  15


Question4

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [9]:
import numpy as np
print("****** Converting 1-D array into 2D array******")
print()
#we can use np.newaxis to increase the dimension of one of the arrays so that NumPy can broadcast.
print("---By using 'np.newaxis' Method---\n")
# 1D array
arr = np.arange(4)
print(arr)
print("Shape of the Array: ",arr.shape)
# make it as row vector by inserting an axis along first dimension
row_vec = arr[np.newaxis, :]     # arr[None, :]
print("Row Vector:")
print("Shape of the array: ",row_vec.shape)
# make it as column vector by inserting an axis along second dimension
col_vec = arr[:, np.newaxis]     # arr[:, None]
print("Column Vector:")
print("Shape of the array: ",col_vec.shape)
print()
#There is another very similar functionality in NumPy: np.expand_dims, which can also be used to insert one dimension:
print("---By Using 'np.expand_dims' Method---\n")
a = np.arange(10)
print(a)
print(np.expand_dims(a, 1))  # like a[:, np.newaxis]
print(np.expand_dims(a, 0))
print()
print("---By Using 'reshape' Method---")
x1 = np.arange(1,10)
print(x1)
print(x1.shape)
print("Dimension: ",x1.ndim)
x1=np.arange(1,10).reshape(3,3)
print(x1)
print(x1.shape)
print("Dimension: ",x1.ndim)

****** Converting 1-D array into 2D array******

---By using 'np.newaxis' Method---

[0 1 2 3]
Shape of the Array:  (4,)
Row Vector:
Shape of the array:  (1, 4)
Column Vector:
Shape of the array:  (4, 1)

---By Using 'np.expand_dims' Method---

[0 1 2 3 4 5 6 7 8 9]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1 2 3 4 5 6 7 8 9]]

---By Using 'reshape' Method---
[1 2 3 4 5 6 7 8 9]
(9,)
Dimension:  1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
Dimension:  2


Question5

Consider two square numpy arrays. Stack them vertically and horizontally.

In [13]:
import numpy as np
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
print("Vertical stacking:\n", np.vstack((a, b)))
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


Question6

How to get unique items and counts of unique items

In [14]:
import numpy as np
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array:\n ', arr)
uniqueValues, occurCount = np.unique(arr, return_counts=True)
print('Unique Values :\n ',uniqueValues)
print("Occurrence Count :\n ", occurCount)
print('Unique Values along with occurrence Count')
listOfUniqueValues = zip(uniqueValues, occurCount)
for elem in listOfUniqueValues:
   print(elem[0] , ' Occurs : ' , elem[1], ' times')

Original Numpy Array:
  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :
  [11 12 13 14 15 16 17 18]
Occurrence Count :
  [3 2 2 2 1 1 1 1]
Unique Values along with occurrence Count
11  Occurs :  3  times
12  Occurs :  2  times
13  Occurs :  2  times
14  Occurs :  2  times
15  Occurs :  1  times
16  Occurs :  1  times
17  Occurs :  1  times
18  Occurs :  1  times
